import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Slidbar from '@/components/Slidbar'
import { getServerSession } from 'next-auth'
import { Sessionprovider } from '@/components/Sessionprovider'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Login from '@/components/Login'
import Clientprovider from '@/components/Clientprovider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions);


  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sessionprovider session={session}>
          {!session ? (
              <Login/>
          ): (
        <div className='flex'>
         <div className="bg-[#202123] max-w-xs h-screen overflow-y- md:min-w-[20rem]">
          <Slidbar/> 
         </div>
         {/* clientprobider*/}
        <Clientprovider/>
         <div className='bg-[#343541] flex-1'>{children}</div>
        </div>
        )}
        </Sessionprovider>
      </body>
    </html>
  )
}
